my_string = input('Введите предложение: ')
print(my_string + '. Длина предложения: ', len(my_string))
print(my_string.upper() + '. В верхнем регистре ".upper()"')
print(my_string.lower() + '. В нижнем регистре ".lower()"')
print(my_string.replace(' ', '') + '. Без пробелов ".replace()"')
print(my_string[0] + '. Первый символ предложения')
print(my_string[-1] + '. Последний символ предложения')